### PR TITLE
Refreshing package cache after PPA added

### PR DESCRIPTION
**Pull request by kmARC**

### CODE REVIEW

**Comment by dein0s** [comment]
Is there any particular cases where it might be useful/needed?
Unlike adding packages via 'apt' module, adding sources differ from system to system (most of them have their own scripts, which uses different python modules). That's why I've implemented this part via executing it in shell with 'subprocess' and therefore we don't need any additional updates as they must be performed under the hood by system script.

To clarify, that's how `add-apt-respository` looks like on Linux Mint:
```python
#!/usr/bin/python3

import os, sys
import gettext
from optparse import OptionParser

gettext.install("mintsources", "/usr/share/linuxmint/locale")

if os.geteuid() != 0:
    print(_("Error: must run as root"))
    sys.exit(1)

usage = "usage: %prog [options] repository"
parser = OptionParser(usage=usage)
parser.add_option("-y", "--yes", dest="forceYes", action="store_true",
    help="force yes on all confirmation questions", default=False)
parser.add_option("-r", "--remove", dest="remove", action="store_true",
    help="Remove the specified repository", default=False)

(options, args) = parser.parse_args()

if (len(args) == 0):
    print(_("Error: need a repository as argument"))
    sys.exit(1)

# Call mintSources script with exec instead of system so that the exit status
# is returned to the caller
mintsources = "/usr/lib/linuxmint/mintSources/mintSources.py"

yes_arg="-?"
if options.forceYes:
    yes_arg="-y"

remove_arg="-?"
if options.remove:
    remove_arg="-r"

os.execl(mintsources, mintsources, "add-apt-repository", yes_arg, remove_arg, args[0])
```

All other magic happens in `/usr/lib/linuxmint/mintSources/mintSources.py` (notice comments in the above code block) and it's too large to post it here.

**Comment by kmARC** [comment]
The reason for me creating this pull request, simply put, is that without refreshing the package cache it simply did not work on my Ubuntu 16.10... It adds the new repo, then fails installing a package from it, bc it can't find in the local cache. I considered this a bug, fixed on my system, thought others could benefit.

**Comment by dein0s** [comment]
Well, first of all, cache is already being updated before adding packages in the main `_process_packages` method ([line 34](https://github.com/dein0s/dotbot_plugin_aptget/blob/master/aptget.py#L34) and [line 35](https://github.com/dein0s/dotbot_plugin_aptget/blob/master/aptget.py#L35)).
Second - you don't need to perform `commit` as you haven't done any changes directly to the `apt.Cache()`.
I'll try to install clean Ubuntu 16.10 and investigate this a bit deeper, but on the first glance - there's nothing wrong with plugin itself, maybe related to some changes in your system.

**Comment by kmARC** [comment]
>  cache is already being updated before adding packages 
That is the problem. It needs to be updated *AFTER* there is a PPA added.

>  you don't need to perform commit
That's what I thought, however, IIRC it did not work without commit :-(

**Comment by dein0s** [comment]
> That is the problem. It needs to be updated **AFTER** there is a PPA added.

Yes, and that's how it is implemented right now (**after** all sources were added and **before** installing packages). Please, take a look at the comments in the following code block:

```python
    def _process_packages(self, packages):
        if os.geteuid() != 0:
            self._log.error('Need root permissions to install packages')
            raise AptGetError('Need root permissions to install packages')
        success = True
        cleaned_packages = self._dispatch_names_and_sources(packages)
        if cleaned_packages['sources']: # Check if there any source in cleaned data from dotbot config file
            for source in cleaned_packages['sources']:  # Add each PPA to the source list
                success &= self._add_ppa(source)
        # Here, after all sources were added, we perform cache update
        self._apt_cache.update()
        self._apt_cache.open() 
        # And finally we begin adding packages
        for pkg_name, upgrade in cleaned_packages['packages'].items():
            success &= self._mark_package_install_upgrade(pkg_name, upgrade)
        try:
            success &= self._apt_cache.commit()
        except Exception as e:
            self._log.error('Failed to install packages: %s' % e)
            success = False
        if success:
            self._log.info('All packages have been installed')
        else:
            self._log.error('Some packages were not successfully installed')
        return success
```

**Comment by dein0s** [comment]
Investigating right now. Can confirm strange behavior of `add-apt-repository` on Ubuntu 16.10.
Right now I already have more elegant solution, but I still don't like it. Will look futher into it.

**Comment by dein0s** [comment]
Gona close this for now and continue in https://github.com/dein0s/dotbot_plugin_aptget/issues/2
I'll mention you when I find a solution for this issue as I don't like changes from this PR. Until then you can stick with your fork :)

**Comment by dein0s** [comment]
Fixed in https://github.com/dein0s/dotbot_plugin_aptget/commit/24f746b103b775b0539a01693275da909728b9a0 and already in master.

**Pull request closed without merging**
